package ventanas;

import BD.Conexion;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import static ventanas.PanelUsuarios.Table_listaUsuarios;
import static ventanas.PanelUsuarios.modelo;
import static ventanas.PanelUsuarios.usuario_update;

/**
 *
 * @author ALEJO
 */
public class PanelTableros extends javax.swing.JPanel {

    
    public static String tablero_update;
    public static DefaultTableModel modelo;
    int Fila;
    
    
    /**
     * Creates new form PanelUsuarios
     */
    public PanelTableros() {
        initComponents();
        
        TableColumnModel columnModel = Table_listaTableros.getColumnModel();

        columnModel.getColumn(0).setPreferredWidth(70);
        columnModel.getColumn(1).setPreferredWidth(30);
        
        
        //Traemos el contenidode la tabla tableros de la BD
        try {
            modelo = new DefaultTableModel();
            Table_listaTableros.setModel(modelo);
            
            Connection cn = Conexion.conectar();
            PreparedStatement pst = cn.prepareStatement(
                        "select Nombre_tablero, Tipo from tableros");
            
            ResultSet rs = pst.executeQuery();
            
            ResultSetMetaData rsmd = rs.getMetaData();
            int cantidadColumnas = rsmd.getColumnCount();
            
            modelo.addColumn("Nombre");
            modelo.addColumn("Tipo");
                                  
            while (rs.next()) {
                
                Object[] filas = new Object[cantidadColumnas];
                
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = rs.getObject(i + 1);
                }
                modelo.addRow(filas);
                }
                cn.close();        
            
            } catch (SQLException e) {
                System.err.println("Error al llenar tabla." + e);
                JOptionPane.showMessageDialog(null, "Error al mostrar información, ¡Contacte al administrador!");
            }

            //Agregamos la funcion de ver informacion del cliente al hacer click sobre el registro de la tabla
            Table_listaTableros.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e){
                int fila_point = Table_listaTableros.rowAtPoint(e.getPoint());
                int columna_point = 0;

                if(fila_point > -1){
                    tablero_update = (String) modelo.getValueAt(fila_point, columna_point);
                    DetalleTablero detalle_tablero = new DetalleTablero();
                    detalle_tablero.setVisible(true);
                }

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btn_nuevoTablero = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_listaTableros = new javax.swing.JTable();
        txt_busqueda = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_mibitacora = new javax.swing.JButton();

        btn_nuevoTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/board.png"))); // NOI18N
        btn_nuevoTablero.setText("Nuevo Tablero");
        btn_nuevoTablero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoTableroActionPerformed(evt);
            }
        });

        Table_listaTableros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nombre", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_listaTableros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Table_listaTableros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_listaTablerosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_listaTableros);

        txt_busqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_busquedaActionPerformed(evt);
            }
        });
        txt_busqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_busquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_busquedaKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Nombre:");

        btn_mibitacora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/taskboard.png"))); // NOI18N
        btn_mibitacora.setText("Mi Bitácora");
        btn_mibitacora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mibitacoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_mibitacora)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_nuevoTablero)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(48, 48, 48))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel2)
                                .addGap(26, 26, 26)
                                .addComponent(txt_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(196, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_nuevoTablero, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(68, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btn_mibitacora, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(199, 199, 199))))
        );
    }// </editor-fold>//GEN-END:initComponents

    //Metodo boton "Nuevo Usuario"
    private void btn_nuevoTableroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoTableroActionPerformed
        new NuevoTablero().setVisible(true);
        btn_nuevoTablero.setEnabled(false);
        
        
    }//GEN-LAST:event_btn_nuevoTableroActionPerformed

    private void txt_busquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busquedaKeyReleased
        String buscar = txt_busqueda.getText();
        busquedaTablero(buscar);
    }//GEN-LAST:event_txt_busquedaKeyReleased

    private void txt_busquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busquedaKeyTyped
        //Forza aescribir en mayuscula
        char c=evt.getKeyChar();
        if(Character.isLowerCase(c)){
            evt.setKeyChar(Character.toUpperCase(c));
        }
    }//GEN-LAST:event_txt_busquedaKeyTyped

    private void txt_busquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_busquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_busquedaActionPerformed

    //Metodo que no hace nada jajajaja
    private void Table_listaTablerosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_listaTablerosMouseClicked
    
    }//GEN-LAST:event_Table_listaTablerosMouseClicked

    private void btn_mibitacoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mibitacoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_mibitacoraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Table_listaTableros;
    public static javax.swing.JButton btn_mibitacora;
    public static javax.swing.JButton btn_nuevoTablero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_busqueda;
    // End of variables declaration//GEN-END:variables

       //Metodo que busca un criterio de busqueda de propietario y carga resultados mientras uno escribe
    public void busquedaTablero(String texto){
        try{
            String [] titulos = {"Nombre", "Tipo"};
            String filtro = ""+texto+"_%";
            String SQL = "select Nombre_tablero, Tipo from tableros where Nombre_tablero like "+'"'+filtro+'"';
            modelo = new DefaultTableModel(null, titulos);
            
            Connection cn6 = Conexion.conectar();
            PreparedStatement pst6 = cn6.prepareStatement(SQL);
            ResultSet rs6 = pst6.executeQuery(SQL);
            
            String[] fila = new String[6];
            
            while(rs6.next()){
                fila[0]=rs6.getString("Nombre_tablero");
                fila[1]=rs6.getString("Tipo");
               
                modelo.addRow(fila);
            }
            Table_listaTableros.setModel(modelo);
            rs6.close();
            cn6.close();
            
        }catch(Exception ex){
            System.err.println("Error en busqueda de tablero." + ex);
            JOptionPane.showMessageDialog(null, "¡¡ERROR de busqueda!!, contacte al administrador.");
        }
    }    




}
